#!/usr/bin/env bash

#   Rawping Installer
#
#   Author: Carlos Uribe <cauribe@nec.com.co>
#   Copyright (C) 2013 NEC de Colombia/NOC-Tx
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Checking prerequisites
if [ `id -u` -eq 0 ]
then
	echo "====== Installing Rawping ======"
  echo "Copying files ..."
  cp python/lib/ping.py /usr/bin
  cp python/rawping /usr/bin
  
  echo "Granting permissions ..."
  chmod ugo+x /usr/bin/rawping
  
  echo "Done!"
else
  echo "You must have root privileges to install rawping."
  echo "Try 'sudo ./install' instead."
fi
