#!/usr/bin/env bash

# Rawping installer.
#
# Author: Carlos Uribe <cm45t3r at gmail.com>
# License MIT.

# Checking prerequisites
if [ `id -u` -eq 0 ]
then
  echo "====== Installing rawping ======"
  echo "Copying files ..."
  cp python/lib/ping.py /usr/bin
  cp python/rawping /usr/bin
  
  echo "Granting permissions ..."
  chmod ugo+x /usr/bin/rawping
  
  echo "Done!"
else
  echo "You must have root privileges to install rawping."
  echo "Run 'sudo ./install'"
fi
