#!/bin/bash

#   Copyright 2013-present NEC de Colombia/TX-NOC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Author: Carlos Uribe <cauribe@nec.com.co>

echo "=== Installing Rawping ==="
echo "Copying files ..."
cp python/lib/ping.py /usr/bin
cp python/rawping /usr/bin
echo "Granting permissions ..."
chmod ugo+x /usr/bin/rawping
echo "Done."
