#!/usr/bin/env python

"""
  Wrapper for Pierre Bourdon's python ping implementation.

  Note that ICMP messages can only be sent from processes running as root.

  Author: Carlos Uribe <cauribe@nec.com.co>
  Copyright (C) 2013-present NEC de Colombia/TX-NOC

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

"""

__version__ = "0.1"

import os
import sys
from ping import *

def usage():
  print 'Usage: rawping <host> <count> <timeout> <packet size>'
  print '   host\t\tip address or qualified network name.'
  print '   count\tnumber of echo requests to send.'
  print '   timeout\tdelay in seconds when there is no answer.'
  print '   packet size\tpayload size in bytes.'
  sys.exit(-1)


if __name__ == '__main__':

    if len(sys.argv) < 4:
      print 'Error: bad argument number.'
      usage()

    if os.geteuid() != 0:
      print 'You must have root privileges to run rawping.'
      sys.exit(-1)

    address = sys.argv[1]
    count = int(sys.argv[2])
    timeout = int(sys.argv[3])
    size = int(sys.argv[4])

    for i in xrange(count):
        try:
            delay = do_one(address, timeout, size)
        except socket.gaierror, e:
            print "Failed. (socket error: '%s')" % e[1]
            break

        if delay == None:
            print delay
        else:
            delay = delay * 1000
            print "%0.4f ms" % delay
