#!/usr/bin/python

"""
   Copyright (C) 2013-present NEC de Colombia/TX-NOC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

"""

# Author: Carlos Uribe <cauribe@nec.com.co>

import sys
from ping import *

if __name__ == '__main__':
    address = sys.argv[1]
    count = int(sys.argv[2])
    timeout = int(sys.argv[3])
    size = int(sys.argv[4])

    for i in xrange(count):
        try:
            delay = do_one(address, timeout, size)
        except socket.gaierror, e:
            print "Failed. (socket error: '%s')" % e[1]
            break

        if delay == None:
            print delay
        else:
            delay = delay * 1000
            print "%0.4f ms" % delay
